# Generated by Django 5.0.3 on 2024-03-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название:')),
                ('description', models.TextField(verbose_name='Описание:')),
                ('date1', models.DateField(verbose_name='Дата начала:')),
                ('date2', models.DateField(verbose_name='Дата окончания:')),
                ('teachers', models.TextField(verbose_name='Учителя:')),
            ],
        ),
    ]
