# Generated by Django 5.0.3 on 2024-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lecture_title',
            field=models.CharField(default=1, max_length=100, verbose_name='Лекции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_video',
            field=models.FileField(default=1, upload_to='lecture/'),
            preserve_default=False,
        ),
    ]
