# Generated by Django 5.0.3 on 2024-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsel', '0002_course_lecture_title_course_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecture_video',
            field=models.FileField(upload_to='media/lecture/'),
        ),
    ]
