# Generated by Django 5.0.3 on 2024-04-02 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marsel', '0003_alter_course_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecture_video',
            field=models.FileField(max_length=5242880, upload_to='media/lectures/'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название задания:')),
                ('description', models.TextField(verbose_name='Описание задания:')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи:')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marsel.course')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='Имя студента:')),
                ('file', models.FileField(upload_to='solutions/')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marsel.exercise')),
            ],
        ),
    ]
